development:
  adapter: postgresql
  database: interism
  pool: 5
  timeout: 5000
test: &test
  adapter: postgresql
  database: interism-test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: interism-production
  pool: 5
  timeout: 5000
